# Generated by Django 4.2 on 2023-04-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="vacancies",
                to="api.company",
            ),
        ),
    ]
