# Generated by Django 4.2 on 2023-04-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_vacancy_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="api.company",
            ),
        ),
    ]
